id: notepad-demo
name: Notepad Demo Workflow
description: Simple workflow demonstrating Phase 1 YAML approach
version: 1.0.0
tags:
  - demo
  - phase1
  - yaml

variables:
  userName:
    type: string
    label: User Name
    description: Name to greet
    default: World
    required: false

  message:
    type: string
    label: Custom Message
    description: Optional custom message
    required: false

steps:
  - id: open-notepad
    name: Open Notepad
    function: openNotepad
    description: Launches Notepad application

  - id: type-greeting
    name: Type Greeting
    function: typeGreeting
    description: Types personalized greeting
    inputs:
      - userName

  - id: add-message
    name: Add Custom Message
    function: addCustomMessage
    description: Adds optional custom message
    condition: variables.message !== ''
    inputs:
      - message
